import{a as w,i as d,S as b}from"./assets/vendor-b0d10f48.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();function v({views:t,downloads:e,likes:s,comments:i,webformatURL:o,largeImageURL:r,tags:n}){return`<li class="card">
      <a class="card-image-wrapper" href="${r}">
        <img class="card-image" src="${o}" alt="${n}" data-full="${r}">
      </a>
      <ul class="card-content">
        <li class="card-content-item">Likes <span data-likes="">${s}</span></li>
        <li class="card-content-item">Comments <span data-comments="">${i}</span></li>
        <li class="card-content-item">Views <span data-views="">${t}</span></li>
        <li class="card-content-item">Downloads <span data-downloads="">${e}</span></li>
      </ul>
    </li>`}function h(t){return t.map(e=>v(e)).join("")}const S=w.create({baseURL:"https://pixabay.com"}),P="/api/";async function g(t,e){t=t.toLowerCase().split(" ").join("+").toString();const s={key:"44424725-c6298a470a26677f9f5105ec2",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15};return(await S.get(P,{params:s})).data}const a={form:document.querySelector(".entry-form"),input:document.querySelector(".entry-form-input"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".next-page")},u={titleColor:"#FFFFFF",messageColor:"#FFFFFF",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",message:"Sorry, there are no images matching<br>your search query.Please try again!",position:"topRight"},M={captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.8},C=15;let l,c=1,p=10,m="";function y(){a.loader.classList.remove("visually-hidden")}function L(){a.loader.classList.add("visually-hidden")}function O(){a.loadMore.classList.remove("visually-hidden")}function f(){a.loadMore.classList.add("visually-hidden")}function $(){const t=a.gallery.children[0].getBoundingClientRect().height,e=24;window.scrollBy({top:2*t+e,behavior:"smooth"})}function F(){c>=p?(f(),p&&d.info({position:"topRight",messageColor:"#FFFFFF",message:"We're sorry, but you've reached<br> the end of search results."})):O()}async function q(t){y(),f(),c=1,a.gallery.innerHTML="";try{const e=await g(t,c);if(e.hits.length===0){d.error(u);return}p=Math.ceil(e.totalHits/C);const s=h(e.hits);a.gallery.innerHTML=s,F(),l=new b(".gallery a",M),l.refresh(),l.on("show.simplelightbox")}catch(e){d.error({...u,message:e.toString()})}finally{L()}}a.form.addEventListener("submit",t=>{t.preventDefault(),m=a.input.value.trim(),q(m),a.form.reset()});a.loadMore.addEventListener("click",async()=>{c++,f(),y();try{const t=await g(m,c),e=h(t.hits);a.gallery.insertAdjacentHTML("beforeend",e),F(),$(),l.refresh(),l.on("show.simplelightbox")}catch(t){d.error({...u,message:t.toString()})}finally{L()}});
//# sourceMappingURL=commonHelpers.js.map
